"""updated models

Revision ID: 32ef822e11f7
Revises: 693a11cd43fe
Create Date: 2025-10-17 01:00:25.976910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ef822e11f7'
down_revision = '693a11cd43fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gradcam_local', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_case', schema=None) as batch_op:
        batch_op.drop_column('gradcam_local')

    # ### end Alembic commands ###
