"""initial schema

Revision ID: 693a11cd43fe
Revises: 
Create Date: 2025-10-16 19:34:24.816081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693a11cd43fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('gradcam_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_case', schema=None) as batch_op:
        batch_op.drop_column('gradcam_url')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
